#
# This file is part of the RCHParamFetcherBundle package.
#
# Robin Chalas <robin.chalas@gmail.com>
#
# For more informations about license, please see the LICENSE
# file distributed in this source code.
#

services:
    # ParamReader
    rch.param_fetcher.reader:
        class: RCH\ParamFetcherBundle\Request\ParamReader
        arguments: [ "@annotation_reader" ]
        public: false

    # ParamFetcher
    rch.param_fetcher.fetcher:
        class: RCH\ParamFetcherBundle\Request\ParamFetcher
        arguments:
            request: "@request_stack"
            validator: "@validator"
            paramReader: "@rch.param_fetcher.reader"

    # ParamListener
    rch.param_fetcher.listener:
        class: RCH\ParamFetcherBundle\EventListener\ParamListener
        arguments: [ "@rch.param_fetcher.fetcher" ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    # ExceptionFormatListener
    rch.param_fetcher.exception_format_listener:
        class: RCH\ParamFetcherBundle\EventListener\ExceptionFormatListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
